-- 113_admin_delete_player_ignore_cancelled_ledger.sql
--
-- Bug: admin_delete_player blocks deletion if a player has ANY
-- payment_ledger row. Mig 082's admin_cancel_match inserts a
-- status='cancelled', amount=0.00 ledger row for every player on
-- the squad each time a match is cancelled. As soon as one match
-- is cancelled, every player on that squad becomes undeletable.
--
-- First hit: session 49 — Footy Tuesdays (team_KPaoX8oJYMQ) admin
-- tried to remove a recently-added duplicate ("Ranza", p_UG2K3Dwp).
-- Ranza had attended=0, no player_match rows, no POTM rows, no
-- injuries — but ONE cancelled, zero-amount ledger row from a
-- cancelled match on 2026-05-26. The has_history guard fired and
-- the client surfaced "Couldn't remove player".
--
-- Fix:
--   1. Tighten the has_history guard so status='cancelled' ledger
--      rows are NOT treated as financial history. Real payments
--      (status IN 'paid','owed','refunded' etc.) still block.
--   2. Cascade-clean cancelled ledger rows in the delete block
--      before deleting the player, so we don't leave orphan
--      rows pointing at a vanished player_id (payment_ledger
--      has no FK on player_id — orphans are silent otherwise).
--
-- No signature change. No grant change. CREATE OR REPLACE keeps
-- PostgREST happy without an explicit DROP. All other guards,
-- audit insert, search_path, SECURITY DEFINER preserved.

CREATE OR REPLACE FUNCTION admin_delete_player(
  p_admin_token text,
  p_player_id   text
) RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_team_id text;
BEGIN
  IF p_admin_token IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'invalid_admin_token';
  END IF;

  SELECT id INTO v_team_id FROM teams WHERE admin_token = p_admin_token;
  IF v_team_id IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'invalid_admin_token';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM team_players WHERE team_id = v_team_id AND player_id = p_player_id
  ) THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'not_found';
  END IF;

  -- §9 guard: block if player has any cross-table history
  -- payment_ledger: only NON-cancelled rows count as financial history.
  -- status='cancelled' rows are auto-generated by admin_cancel_match
  -- (mig 082) and carry no financial weight (amount=0).
  IF (
    COALESCE((SELECT attended FROM players WHERE id = p_player_id), 0) > 0
    OR EXISTS (SELECT 1 FROM player_match WHERE player_id = p_player_id)
    OR EXISTS (
      SELECT 1 FROM payment_ledger
      WHERE player_id = p_player_id
        AND status <> 'cancelled'
    )
    OR EXISTS (
      SELECT 1 FROM potm_votes
      WHERE voter_id = p_player_id OR nominee_id = p_player_id
    )
    OR EXISTS (SELECT 1 FROM player_injuries WHERE player_id = p_player_id)
  ) THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'has_history';
  END IF;

  INSERT INTO audit_events (
    team_id, actor_type, actor_user_id, actor_identifier,
    action, entity_type, entity_id, metadata
  ) VALUES (
    v_team_id, 'team_admin', auth.uid(),
    'admin_token:' || md5(p_admin_token),
    'player_deleted', 'player', p_player_id,
    jsonb_build_object('player_id', p_player_id)
  );

  -- Cascade order: referencing rows first, players row last.
  DELETE FROM team_players
  WHERE  player_id = p_player_id
    AND  team_id   = v_team_id;

  DELETE FROM player_injuries
  WHERE  player_id = p_player_id
    AND  team_id   = v_team_id;

  DELETE FROM push_subscriptions
  WHERE  player_id = p_player_id;

  DELETE FROM player_career WHERE player_id = p_player_id;

  -- Clean cancelled ledger rows so we don't orphan them. Non-cancelled
  -- rows would have been caught by the has_history guard above.
  DELETE FROM payment_ledger
  WHERE  player_id = p_player_id
    AND  status    = 'cancelled';

  DELETE FROM players WHERE id = p_player_id;

  PERFORM notify_team_change(v_team_id, 'player_deleted');

  RETURN jsonb_build_object('ok', true);
EXCEPTION
  WHEN OTHERS THEN
    IF SQLSTATE = 'P0001' THEN RAISE; END IF;
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'internal_error';
END;
$$;

REVOKE EXECUTE ON FUNCTION admin_delete_player(text, text) FROM public;
GRANT  EXECUTE ON FUNCTION admin_delete_player(text, text) TO anon, authenticated;
