-- 581_superadmin_import_club_roster.sql
--
-- DF Sports Onboarding — PR #4, the single-club member/child/guardian bulk import.
--
-- superadmin_import_club_roster is the OPERATOR-LED bulk roster importer: a
-- platform admin pastes a club's roster (children + their guardians) and it is
-- provisioned in one atomic call — child shells into member_profiles, guardian
-- shells + parent↔child links into member_guardians, an age-band membership per
-- child into venue_memberships with cohort_id auto-placed via _cohort_for_dob
-- (mig 580). It is the tool that stands DF up populated (its first use is a
-- personalised demo for the owner; the same RPC later imports the real roster).
--
-- This is a BESPOKE importer for exactly three tables — NOT the generic import
-- engine (CLIENT_ONBOARDING_IMPORT_HANDOFF.md). It inherits that doc's SAFETY
-- PATTERNS only:
--   * Unclaimed shells — auth_user_id / person_id are NEVER set (omitted → NULL).
--     A guardian claims their profile later via the existing email-match sign-in
--     flow (member_claim_profile); this import grants NOBODY access.
--   * Zero consent — the consent/safeguarding columns
--     (consent_emergency_treatment, consent_administer_medication,
--     may_leave_unaccompanied, photo_consent) are NOT NULL DEFAULT, and the
--     import sets NONE of them (they stay at the safe DB default). Decision 13's
--     "represents_person" rule is enforced HARD: any payload row (child OR
--     guardian) carrying a forbidden identity/consent key is rejected outright
--     (consent_fields_forbidden) rather than silently ignored.
--   * Legal basis sits with the club (contract / legitimate interest), never the
--     import act — nothing here records or fabricates consent.
--   * Upsert-by-natural-key — re-running the same file UPDATES, never duplicates.
--     No DB natural key exists on member_profiles / venue_memberships, so the key
--     is enforced in-body: a child by (this venue's members) + name + dob; a
--     guardian by exact lower(email) among this club's existing guardian links
--     (so siblings share one guardian profile). Cross-club person-matching is
--     deliberately NOT done — that is the sign-in claim flow's job.
--   * Row-level partial failure inside one atomic transaction (Decisions 3 + 26):
--     each row runs in its own sub-block; a bad row is reported and produces zero
--     writes (rolled back to its savepoint) but never aborts the good rows. The
--     whole call still commits (or rolls back) as one transaction. Per-row counts
--     are folded into the totals ONLY after a row fully succeeds — plpgsql's
--     EXCEPTION rolls back DB writes but NOT variable assignments, so counting
--     mid-row would over-report a partially-failed row.
--   * No venue_charges written (Decision 22 — never fabricate billing history).
--     An active membership's genuine dues are generated by the real renewal cron;
--     all stripe_*/gc_* fields stay NULL (cash / bank-transfer membership).
--
-- COHORT PLACEMENT: the ONLY home for a child↔age-band link is
-- venue_memberships.cohort_id (there is no cohort-member join table). So the
-- membership row is REQUIRED to record placement; _cohort_for_dob(club, dob)
-- (mig 580) fills cohort_id. dob absent → cohort NULL + a warning; dob present
-- but outside every band → cohort NULL + a warning (both non-fatal).
--
-- MEMBERSHIP MONEY MODEL (operator decision A, 2026-07-15): imported memberships
-- are p_status (default 'active') on a real club tier + its venue_tier_prices
-- price. This reflects genuine ongoing enrolment (DF's £/term members) and is
-- NOT fabricated billing; NO card is ever charged (Stripe dormant until live
-- keys). pricing_model is derived from the period (season → 'term', else
-- 'recurring') so the venue_memberships CHECK (recurring|term) is satisfied
-- regardless of the tier's own pricing_model (recurring|season). p_status='paused'
-- imports roster + cohort only, invisible to the renewal cron.
--
-- SECURITY — mirrors mig 578 / mig 085:
--   * SECURITY DEFINER, search_path pinned (public, pg_temp).
--   * is_platform_admin() gate; anon REVOKEd BY NAME (Supabase default-privileges
--     auto-grant anon; REVOKE FROM PUBLIC does not strip it).
--   * NEVER trusts a client-supplied identity — the child/guardian person rows are
--     minted server-side; no auth_user_id/person_id is accepted from the payload.
--   * Canonical audit_events row per import batch, actor_type='platform_admin'
--     (CHECK-valid, mig 085), carrying the batch id + all counts.
--
-- Consumers (HR#14): apps/superadmin (future import UI, PR-later) + platform-admin
-- CLI/console. Not client-callable by anon or ordinary authenticated users.
--
-- Reuses existing columns only — no schema change beyond this function.
-- Paired teardown: 581_superadmin_import_club_roster_down.sql

CREATE OR REPLACE FUNCTION public.superadmin_import_club_roster(
  p_venue_id text,
  p_tier_id  uuid,
  p_period   text,
  p_rows     jsonb,
  p_status   text DEFAULT 'active'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
DECLARE
  v_uid        uuid := auth.uid();
  v_club_id    text;
  v_tier       record;
  v_price      int;
  v_pricing    text;
  v_renews     date;
  v_batch      uuid := gen_random_uuid();
  v_forbidden  text[] := ARRAY[
    'auth_user_id','person_id','source_customer_id',
    'consent_emergency_treatment','consent_administer_medication',
    'may_leave_unaccompanied','photo_consent'
  ];
  v_row        jsonb;
  v_guardian   jsonb;
  v_idx        int := 0;
  v_dob        date;
  v_child_id   uuid;
  v_existing   uuid;
  v_guardian_id uuid;
  v_payer_id   uuid;
  v_cohort_id  uuid;
  v_mid        uuid;
  v_first_g    boolean;
  -- per-row locals (folded into totals only on full row success)
  r_child_created int; r_child_updated int; r_guard_created int; r_guard_linked int;
  r_mem_created int; r_mem_updated int; r_cohort int; r_warning jsonb;
  -- global counters
  c_child_created int := 0; c_child_updated int := 0;
  c_guard_created int := 0; c_guard_linked int := 0;
  c_mem_created int := 0; c_mem_updated int := 0;
  c_cohorts int := 0; c_failed int := 0;
  v_rows_out jsonb := '[]'::jsonb;
  v_warnings jsonb := '[]'::jsonb;
BEGIN
  -- ── Auth gate — platform admins only (anon REVOKEd below; defend in depth) ──
  IF v_uid IS NULL OR NOT public.is_platform_admin() THEN
    RAISE EXCEPTION 'not_platform_admin' USING ERRCODE = 'P0001';
  END IF;

  -- ── Whole-call validation (these fail the entire import) ──
  IF p_rows IS NULL OR jsonb_typeof(p_rows) <> 'array' OR jsonb_array_length(p_rows) = 0 THEN
    RAISE EXCEPTION 'rows_required' USING ERRCODE = 'P0001';
  END IF;
  IF p_status IS NULL OR p_status NOT IN ('active','paused') THEN
    RAISE EXCEPTION 'invalid_status' USING ERRCODE = 'P0001';
  END IF;
  IF p_period IS NULL OR p_period NOT IN ('monthly','quarterly','annual','season') THEN
    RAISE EXCEPTION 'invalid_period' USING ERRCODE = 'P0001';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.venues WHERE id = p_venue_id) THEN
    RAISE EXCEPTION 'venue_not_found' USING ERRCODE = 'P0001';
  END IF;

  SELECT cv.club_id INTO v_club_id
  FROM public.club_venues cv
  WHERE cv.venue_id = p_venue_id
  ORDER BY cv.club_id
  LIMIT 1;
  IF v_club_id IS NULL THEN
    RAISE EXCEPTION 'venue_has_no_club' USING ERRCODE = 'P0001';
  END IF;

  SELECT t.id, t.season_end INTO v_tier
  FROM public.venue_membership_tiers t
  WHERE t.id = p_tier_id AND t.venue_id = p_venue_id AND t.active;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'tier_not_found' USING ERRCODE = 'P0001';
  END IF;

  SELECT p.price_pence INTO v_price
  FROM public.venue_tier_prices p
  WHERE p.tier_id = p_tier_id AND p.period = p_period AND p.active
    AND p.price_type = 'standard'
  ORDER BY p.price_pence
  LIMIT 1;
  IF v_price IS NULL THEN
    RAISE EXCEPTION 'price_not_set' USING ERRCODE = 'P0001';
  END IF;

  v_pricing := CASE WHEN p_period = 'season' THEN 'term' ELSE 'recurring' END;
  v_renews  := CASE WHEN p_period = 'season'
                    THEN COALESCE(v_tier.season_end, '9999-12-31'::date)
                    ELSE current_date + public._membership_period_interval(p_period) END;

  -- ── Per-row processing (row-level partial failure inside the one transaction) ──
  FOR v_row IN SELECT value FROM jsonb_array_elements(p_rows)
  LOOP
    v_idx := v_idx + 1;
    r_child_created := 0; r_child_updated := 0; r_guard_created := 0; r_guard_linked := 0;
    r_mem_created := 0; r_mem_updated := 0; r_cohort := 0; r_warning := NULL;
    BEGIN
      -- represents_person HARD-BLOCK: no identity/consent column may arrive by payload
      IF v_row ?| v_forbidden THEN
        RAISE EXCEPTION 'consent_fields_forbidden' USING ERRCODE = 'P0001';
      END IF;
      IF COALESCE(btrim(v_row->>'first_name'),'') = '' THEN
        RAISE EXCEPTION 'first_name_required' USING ERRCODE = 'P0001';
      END IF;
      v_dob := NULLIF(btrim(v_row->>'dob'),'')::date;

      -- 1. Child upsert by natural key: name + dob among THIS venue's members
      SELECT mp.id INTO v_existing
      FROM public.member_profiles mp
      WHERE lower(btrim(mp.first_name)) = lower(btrim(v_row->>'first_name'))
        AND lower(btrim(COALESCE(mp.last_name,''))) = lower(btrim(COALESCE(v_row->>'last_name','')))
        AND mp.dob IS NOT DISTINCT FROM v_dob
        AND EXISTS (
          SELECT 1 FROM public.venue_memberships vm
          WHERE vm.member_profile_id = mp.id AND vm.venue_id = p_venue_id
        )
      ORDER BY mp.created_at
      LIMIT 1;

      IF v_existing IS NOT NULL THEN
        v_child_id := v_existing;
        UPDATE public.member_profiles mp SET
          last_name          = COALESCE(NULLIF(btrim(v_row->>'last_name'),''), mp.last_name),
          dob                = COALESCE(v_dob, mp.dob),
          gender             = COALESCE(NULLIF(btrim(v_row->>'gender'),''), mp.gender),
          medical_conditions = COALESCE(NULLIF(btrim(v_row->>'medical_conditions'),''), mp.medical_conditions),
          allergies          = COALESCE(NULLIF(btrim(v_row->>'allergies'),''), mp.allergies),
          medications        = COALESCE(NULLIF(btrim(v_row->>'medications'),''), mp.medications),
          ec1_name           = COALESCE(NULLIF(btrim(v_row->>'ec1_name'),''), mp.ec1_name),
          ec1_relationship   = COALESCE(NULLIF(btrim(v_row->>'ec1_relationship'),''), mp.ec1_relationship),
          ec1_phone          = COALESCE(NULLIF(btrim(v_row->>'ec1_phone'),''), mp.ec1_phone),
          updated_at         = now()
        WHERE mp.id = v_child_id;
        r_child_updated := 1;
      ELSE
        INSERT INTO public.member_profiles (
          first_name, last_name, dob, gender,
          medical_conditions, allergies, medications,
          ec1_name, ec1_relationship, ec1_phone
        ) VALUES (
          btrim(v_row->>'first_name'),
          NULLIF(btrim(v_row->>'last_name'),''),
          v_dob,
          NULLIF(btrim(v_row->>'gender'),''),
          NULLIF(btrim(v_row->>'medical_conditions'),''),
          NULLIF(btrim(v_row->>'allergies'),''),
          NULLIF(btrim(v_row->>'medications'),''),
          NULLIF(btrim(v_row->>'ec1_name'),''),
          NULLIF(btrim(v_row->>'ec1_relationship'),''),
          NULLIF(btrim(v_row->>'ec1_phone'),'')
        ) RETURNING id INTO v_child_id;
        r_child_created := 1;
      END IF;

      -- 2. Guardians — shell + accepted link; siblings share one guardian profile
      v_payer_id := NULL;
      v_first_g  := true;
      IF jsonb_typeof(v_row->'guardians') = 'array' THEN
        FOR v_guardian IN SELECT value FROM jsonb_array_elements(v_row->'guardians')
        LOOP
          IF v_guardian ?| v_forbidden THEN
            RAISE EXCEPTION 'consent_fields_forbidden' USING ERRCODE = 'P0001';
          END IF;
          IF COALESCE(btrim(v_guardian->>'first_name'),'') = '' THEN
            CONTINUE;  -- skip an empty guardian entry
          END IF;

          -- Guardian natural key, club-scoped so it never attaches to a
          -- stranger's profile: exact email when present, else name+phone
          -- (so a phone-only guardian on a real roster still de-dupes on re-run).
          v_guardian_id := NULL;
          IF NULLIF(btrim(v_guardian->>'email'),'') IS NOT NULL THEN
            SELECT g.id INTO v_guardian_id
            FROM public.member_profiles g
            WHERE lower(btrim(g.email)) = lower(btrim(v_guardian->>'email'))
              AND EXISTS (
                SELECT 1 FROM public.member_guardians mg
                JOIN public.venue_memberships vm ON vm.member_profile_id = mg.child_profile_id
                WHERE mg.guardian_profile_id = g.id AND vm.venue_id = p_venue_id
              )
            ORDER BY g.created_at
            LIMIT 1;
          ELSIF NULLIF(btrim(v_guardian->>'phone'),'') IS NOT NULL THEN
            SELECT g.id INTO v_guardian_id
            FROM public.member_profiles g
            WHERE lower(btrim(COALESCE(g.first_name,''))) = lower(btrim(v_guardian->>'first_name'))
              AND lower(btrim(COALESCE(g.last_name,''))) = lower(btrim(COALESCE(v_guardian->>'last_name','')))
              AND btrim(COALESCE(g.phone,'')) = btrim(v_guardian->>'phone')
              AND EXISTS (
                SELECT 1 FROM public.member_guardians mg
                JOIN public.venue_memberships vm ON vm.member_profile_id = mg.child_profile_id
                WHERE mg.guardian_profile_id = g.id AND vm.venue_id = p_venue_id
              )
            ORDER BY g.created_at
            LIMIT 1;
          END IF;

          IF v_guardian_id IS NULL THEN
            INSERT INTO public.member_profiles (first_name, last_name, email, phone)
            VALUES (
              btrim(v_guardian->>'first_name'),
              NULLIF(btrim(v_guardian->>'last_name'),''),
              NULLIF(btrim(v_guardian->>'email'),''),
              NULLIF(btrim(v_guardian->>'phone'),'')
            ) RETURNING id INTO v_guardian_id;
            r_guard_created := r_guard_created + 1;
          END IF;

          INSERT INTO public.member_guardians (
            child_profile_id, guardian_profile_id, relationship,
            is_primary, can_collect, invite_state, accepted_at
          ) VALUES (
            v_child_id, v_guardian_id,
            NULLIF(btrim(v_guardian->>'relationship'),''),
            COALESCE((v_guardian->>'is_primary')::boolean, v_first_g),
            COALESCE((v_guardian->>'can_collect')::boolean, true),
            'accepted', now()
          )
          ON CONFLICT (child_profile_id, guardian_profile_id) DO UPDATE SET
            relationship = COALESCE(EXCLUDED.relationship, member_guardians.relationship),
            is_primary   = EXCLUDED.is_primary,
            can_collect  = EXCLUDED.can_collect;
          r_guard_linked := r_guard_linked + 1;

          IF v_payer_id IS NULL OR COALESCE((v_guardian->>'is_primary')::boolean, false) THEN
            v_payer_id := v_guardian_id;
          END IF;
          v_first_g := false;
        END LOOP;
      END IF;

      -- 3. Cohort placement (age band from dob; non-fatal when unplaceable)
      v_cohort_id := public._cohort_for_dob(v_club_id, v_dob);
      IF v_cohort_id IS NOT NULL THEN
        r_cohort := 1;
      ELSIF v_dob IS NULL THEN
        r_warning := jsonb_build_object('index', v_idx, 'warning', 'no_dob_cohort_unplaced');
      ELSE
        r_warning := jsonb_build_object('index', v_idx, 'warning', 'no_matching_age_band');
      END IF;

      -- 4. Membership upsert — one live membership per child at this venue
      SELECT vm.id INTO v_mid
      FROM public.venue_memberships vm
      WHERE vm.venue_id = p_venue_id
        AND vm.member_profile_id = v_child_id
        AND vm.status IN ('active','paused','ending')
      ORDER BY vm.created_at
      LIMIT 1;

      IF v_mid IS NOT NULL THEN
        UPDATE public.venue_memberships vm SET
          tier_id          = p_tier_id,
          period           = p_period,
          amount_pence     = v_price,
          status           = p_status,
          pricing_model    = v_pricing,
          club_id          = v_club_id,
          cohort_id        = v_cohort_id,
          payer_profile_id = v_payer_id,
          renews_at        = v_renews,
          updated_at       = now()
        WHERE vm.id = v_mid;
        r_mem_updated := 1;
      ELSE
        INSERT INTO public.venue_memberships (
          venue_id, tier_id, period, amount_pence, status, renews_at,
          club_id, member_profile_id, payer_profile_id, cohort_id, pricing_model
        ) VALUES (
          p_venue_id, p_tier_id, p_period, v_price, p_status, v_renews,
          v_club_id, v_child_id, v_payer_id, v_cohort_id, v_pricing
        ) RETURNING id INTO v_mid;
        r_mem_created := 1;
      END IF;

      -- Row fully succeeded — fold per-row counts into the totals
      c_child_created := c_child_created + r_child_created;
      c_child_updated := c_child_updated + r_child_updated;
      c_guard_created := c_guard_created + r_guard_created;
      c_guard_linked  := c_guard_linked  + r_guard_linked;
      c_mem_created   := c_mem_created    + r_mem_created;
      c_mem_updated   := c_mem_updated    + r_mem_updated;
      c_cohorts       := c_cohorts        + r_cohort;
      IF r_warning IS NOT NULL THEN
        v_warnings := v_warnings || r_warning;
      END IF;

      v_rows_out := v_rows_out || jsonb_build_object(
        'index', v_idx,
        'status', CASE WHEN r_child_updated = 1 THEN 'updated' ELSE 'created' END,
        'child_profile_id', v_child_id,
        'membership_id', v_mid,
        'cohort_id', v_cohort_id
      );
    EXCEPTION WHEN OTHERS THEN
      c_failed := c_failed + 1;
      v_rows_out := v_rows_out || jsonb_build_object(
        'index', v_idx, 'status', 'error', 'reason', SQLERRM
      );
    END;
  END LOOP;

  -- ── Audit — canonical columns; one row per import batch ──
  INSERT INTO public.audit_events (
    team_id, actor_user_id, actor_type, actor_identifier,
    action, entity_type, entity_id, metadata
  ) VALUES (
    p_venue_id, v_uid, 'platform_admin', 'user_id:' || v_uid::text,
    'club_roster_imported', 'venue', p_venue_id,
    jsonb_build_object(
      'import_batch_id',    v_batch,
      'club_id',            v_club_id,
      'tier_id',            p_tier_id,
      'period',             p_period,
      'status',             p_status,
      'rows_total',         v_idx,
      'children_created',   c_child_created,
      'children_updated',   c_child_updated,
      'guardians_created',  c_guard_created,
      'guardians_linked',   c_guard_linked,
      'memberships_created', c_mem_created,
      'memberships_updated', c_mem_updated,
      'cohorts_placed',     c_cohorts,
      'rows_failed',        c_failed
    )
  );

  PERFORM public.notify_venue_change(p_venue_id, 'roster_imported');

  RETURN jsonb_build_object(
    'ok', true,
    'import_batch_id', v_batch,
    'summary', jsonb_build_object(
      'rows_total',          v_idx,
      'children_created',    c_child_created,
      'children_updated',    c_child_updated,
      'guardians_created',   c_guard_created,
      'guardians_linked',    c_guard_linked,
      'memberships_created', c_mem_created,
      'memberships_updated', c_mem_updated,
      'cohorts_placed',      c_cohorts,
      'rows_failed',         c_failed
    ),
    'rows', v_rows_out,
    'warnings', v_warnings
  );
END;
$function$;

-- Grants: authenticated-only surface; the is_platform_admin() gate does the real
-- work inside. Strip PUBLIC and the auto-granted anon explicitly.
REVOKE ALL ON FUNCTION public.superadmin_import_club_roster(text, uuid, text, jsonb, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.superadmin_import_club_roster(text, uuid, text, jsonb, text) FROM anon;
GRANT EXECUTE ON FUNCTION public.superadmin_import_club_roster(text, uuid, text, jsonb, text) TO authenticated;
